version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: wb_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.5.0
    container_name: wb_dbt
    profiles: [ "dbt-only" ] # Запускаем по требованию
    volumes:
      - ./dbt_project:/usr/app/dbt
    environment:
      DBT_PROFILES_DIR: /usr/app/dbt
    depends_on:
      - postgres_db
    working_dir: /usr/app/dbt

volumes:
  pgdata: